#' Computer cluster-specific metadata
#'
#' `fa_clusterDiversity` returns the following metadata per cluster: unique sequence count, total read count, total RPU, average LED, and Simpson's index of diversity.
#'
#' @param faDF_cluster A clustered data.frame generated by fa_clusterLED
#'
#' @seealso [fa_clusterLED()], [fa_clusterDiversity_metaplot()], [fa_clusterDiversity_kmer()]
#'
#' @return A data.frame that includes metadata for each cluster, including total unique sequences, total reads, total RPU, average LED, and Simpson's index of diversity
#' @export
#'
#' @examples
#' \dontrun{
#' # count FASTQ file, cluster data, compute metadata
#' countData <- fa_count(dataInput = "PATH/TO/FILE.fastq")
#' clusterData <- fa_clusterLED(
#'   faDF = countData,
#'   minReads = 5,
#'   maxLED = 10,
#'   totalClusters = 100,
#'   keepNC = FALSE
#' )
#' cluster_metadata <- fa_clusterDiversity(faDF_cluster = clusterData)
#' }
#'
#' @importFrom dplyr %>%
#' @importFrom rlang .data
fa_clusterDiversity <- function(faDF_cluster = NULL){

  # get summary features per cluster, sort by cluster
  clusterStats <- faDF_cluster %>%
    dplyr::group_by(.data$Cluster) %>%
    dplyr::summarise(
      TotalSequences = dplyr::n(),
      TotalReads = sum(.data$Reads),
      TotalRPU = sum(.data$RPU),
      AverageLED = round(mean(.data$LED), 2),
      SID = round(1 - sum(.data$Reads * (.data$Reads - 1)) / (sum(.data$Reads) * (sum(.data$Reads) - 1)), 2)
    ) %>%
    dplyr::arrange(.data$Cluster)

  # add cluster seeds with their IDs
  clusterStats <- clusterStats %>%
    dplyr::left_join(
      faDF_cluster %>% dplyr::filter(.data$RankInCluster == 1) %>% dplyr::select(.data$Cluster, .data$ID, .data$Sequences),
      by = "Cluster"
    )

  # return data.frame with clustering metadata
  return(clusterStats)
}
