#' This function returns the clusters available in the input data
#'
#' @param clusterPath The file path to a clustered FASTA file
#'
#' @return A vector of clusters found in the file
#'
#' @importFrom dplyr %>%
#' @importFrom rlang .data
fa_getClusters <- function(clusterPath = NULL){

  # input checks
  stopifnot(
    file.exists(clusterPath)
  )

  # read data and get available clusters
  available_clusters <- fa_formatInput(fastaInput = clusterPath) %>%
    dplyr::pull(.data$Cluster) %>%
    unique()

  # return available clusters
  return(available_clusters)
}

#' Perform an MSA for a single cluster of sequences
#'
#' `fa_clusterMSA` performs a DNA (default) or protein multiple sequence alignment (MSA) with the `msa` package.
#'
#' @param faDF_cluster A clustered data.frame generated by fa_clusterLED
#' @param clusterSelection A single integer representing the cluster to be aligned (default: 1)
#' @param seq_type One of dna or protein (default: "dna")
#'
#' @seealso [fa_clusterLED()], [fa_clusterMSA_entropy()], [fa_clusterMSA_mutInfo()], [msa::msa()]
#'
#' @return A single cluster in a data.frame that includes aligned sequences
#' @export
#'
#' @examples
#' \dontrun{
#' # count FASTQ file, cluster data, perform MSA
#' countData <- fa_count(dataInput = "PATH/TO/FILE.fastq")
#' clusterData <- fa_clusterLED(faDF = countData)
#' msaData <- fa_clusterMSA(faDF_cluster = clusterData, clusterSelection = 10, seq_type = "dna")
#' }
#'
#' @importFrom dplyr %>%
#' @importFrom rlang .data
fa_clusterMSA <- function(faDF_cluster = NULL, clusterSelection = 1, seq_type = "dna"){

  # bind variables
  ID <- Sequences <- NULL

  # filter for cluster and perform MSA
  msa_vector <- faDF_cluster %>%
    dplyr::filter(.data$Cluster == clusterSelection) %>%
    dplyr::pull(.data$Sequences, name = .data$ID) %>%
    msa::msa(type = seq_type, order = "input") %>%
    as.character()

  # convert MSA vector to a data.frame
  msa_df <- data.frame(
    ID = names(msa_vector),
    Sequences = unname(msa_vector)
  ) %>%
    dplyr::left_join(faDF_cluster %>% dplyr::select(-.data$Sequences), by = "ID") %>%
    dplyr::relocate(.data$Sequences, .after = dplyr::last_col()) %>%
    dplyr::arrange(.data$Rank)

  # return data.frame with one cluster after MSA
  return(msa_df)
}
