#' Return a bar chart showing the entropy per position of an alignment
#'
#' `fa_clusterMSA_entropy` returns a bar chart that shows the entropy at every position of an aligned cluster.
#'
#' @param msa_df A data.frame generated by `fa_clusterMSA`
#' @param xaxis The x-axis title (default: "MSA position")
#' @param yaxis The y-axis title (default: "Entropy (nats)")
#' @param legend_title The legend title (default: "Nats")
#' @param plot_title The plot title (default: "Entrpy by position in MSA")
#' @param bar_outline The color of the bar outlines (default: "black")
#' @param bar_fill The color of the bar fills (default: "skyblue")
#'
#' @seealso [grDevices::colors()], [fa_clusterMSA()], [fa_clusterLED()], [fa_clusterMSA_mutInfo()]
#'
#' @return A plotly object with a bar chart showing the entropy at every position of the alignment
#' @export
#'
#' @examples
#' \dontrun{
#' # count FASTQ file, cluster data, generate MSA
#' countData <- fa_count(dataInput = "PATH/TO/FILE.fastq")
#' clusterData <- fa_clusterLED(faDF = countData)
#' msaData <- fa_clusterMSA(faDF_cluster = clusterData)
#'
#' # plot MSA entropy
#' fa_clusterMSA_entropy(msa_df = msa_df)
#' }
#'
#' @importFrom dplyr %>%
#' @importFrom rlang .data
fa_clusterMSA_entropy <- function(
    msa_df = NULL,
    xaxis = "MSA position",
    yaxis = "Entropy (nats)",
    legend_title = "Nats",
    plot_title = "Entropy by position in MSA",
    bar_outline = "black",
    bar_fill = "skyblue"
){

  # input checks
  stopifnot(
    is.data.frame(msa_df),
    nrow(msa_df) >= 1,

    is.character(xaxis),
    length(xaxis) == 1,

    is.character(yaxis),
    length(yaxis) == 1,

    is.character(plot_title),
    length(plot_title) == 1,

    length(bar_outline) == 1,
    bar_outline %in% grDevices::colors(),

    length(bar_fill) == 1,
    bar_fill %in% grDevices::colors()
  )

  # split sequences by character into matrix
  msa_matrix <- matrix(
    data = unlist(strsplit(msa_df$Sequences, split = "")),
    nrow = nrow(msa_df),
    ncol = nchar(msa_df$Sequences[1]),
    byrow = TRUE
  )

  # get entropy for each column of the alignment
  msa_SE <- sapply(1:ncol(msa_matrix), function(x) infotheo::entropy(X = msa_matrix[,x]))

  # make data.frame
  msa_SE_DF <- data.frame(Residue = 1:length(msa_SE), SE = msa_SE)

  # plot SE of MSA
  p <- ggplot2::ggplot(
    msa_SE_DF,
    ggplot2::aes(
      .data$Residue,
      .data$SE,
      text = glue::glue("Residue: {Residue}, Shannon Entropy (nats): {round(SE, 3)}")
    )
  ) +
    ggplot2::geom_bar(stat = "identity", colour = bar_outline, fill = bar_fill) +
    ggplot2::labs(x = xaxis, y = yaxis, fill = legend_title, title = plot_title) +
    ggplot2::theme_bw()

  # make plot bold
  p <- boldPlots(p)

  # make plot interactive
  fig <- plotly::ggplotly(p, tooltip = "text") %>%
    plotly::config(toImageButtonOptions = list(format = "svg", filename = "MSA_entropy"))

  # return figure
  return(fig)
}

#' Return a mutual information heat map
#'
#' `fa_clusterMSA_mutInfo` returns a heat map showing the mutual information between pairs of positions in aligned sequences.
#'
#' @param msa_df A data.frame generated by `fa_clusterMSA`
#' @param xaxis The x-axis title (default: "MSA position")
#' @param yaxis The y-axis title (default: "MSA position")
#' @param legend_title The legend title (default: "MI")
#' @param plot_title The plot title (default: "Pairwise mutual information in MSA")
#' @param fill_palette_cont A continuous color palette (default: "magma")
#'
#' @seealso [ggplot2::scale_fill_viridis_c()], [fa_clusterMSA()], [fa_clusterLED()], [fa_clusterMSA_entropy()]
#'
#' @return A plotly object with a heat map showing the mutual information between all pairs of positions in the alignment
#' @export
#'
#' @examples
#' \dontrun{
#' # count FASTQ file, cluster data, generate MSA
#' countData <- fa_count(dataInput = "PATH/TO/FILE.fastq")
#' clusterData <- fa_clusterLED(faDF = countData)
#' msaData <- fa_clusterMSA(faDF_cluster = clusterData)
#'
#' # plot MSA mutual information
#' fa_clusterMSA_mutInfo(msa_df = msa_df)
#' }
#'
#' @importFrom dplyr %>%
#' @importFrom rlang .data
fa_clusterMSA_mutInfo <- function(
    msa_df = NULL,
    xaxis = "MSA position",
    yaxis = "MSA position",
    legend_title = "MI",
    plot_title = "Pairwise mutual information in MSA",
    fill_palette_cont = "magma"
){

  # split sequences by character into matrix
  msa_matrix <- matrix(
    data = unlist(strsplit(msa_df$Sequences, split = "")),
    nrow = nrow(msa_df),
    ncol = nchar(msa_df$Sequences[1]),
    byrow = TRUE
  )

  # get mutual information for every pair of columns
  msa_MI <- infotheo::mutinformation(X = as.data.frame(msa_matrix))

  # plot MI of MSA
  p <- msa_MI %>%
    tibble::as_tibble() %>%
    tibble::rowid_to_column(var = "x") %>%
    tidyr::gather(key = "y", value = "z", -1) %>%
    dplyr::mutate(y = gsub("V", "", .data$y) %>% as.numeric()) %>%

    ggplot2::ggplot(
      ggplot2::aes(
        x = .data$x, y = .data$y, fill = .data$z,
        text = glue::glue("MSA position 1: {x}, MSA position 2: {y}, Mutual Information: {round(z, 3)}")
      )
    ) +
    ggplot2::geom_tile() +
    ggplot2::scale_fill_viridis_c(option = fill_palette_cont) +
    ggplot2::labs(x = xaxis, y = yaxis, fill = legend_title, title = plot_title) +
    ggplot2::theme_classic()

  # make plot bold
  p <- boldPlots(p)

  # make interactive figure
  fig <- plotly::ggplotly(p, tooltip = "text") %>%
    plotly::config(toImageButtonOptions = list(format = "svg", filename = "MSA_mutualInformation"))

  # return figure
  return(fig)
}
